version: '2'

services:
  postgres:
    restart: always
    container_name: postgres_server
    build: ./docker/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    ports:
      - "5100:5432"
    env_file: .env

  django:
    restart: always
    container_name: django_server
    build:
      context: .
      dockerfile: ./docker/django/development/Dockerfile
    command: /start.sh
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    links:
      - postgres

  nginx:
    restart: always
    container_name: nginx_server
    build:
      context: .
      dockerfile: ./docker/nginx/development/Dockerfile
    depends_on:
      - django
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"

volumes:
  postgres_data_dev:
    driver: local
  postgres_backup_dev:
    driver: local
