version: '2'

services:
  postgres:
    container_name: postgres_server
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    ports:
      - "5100:5432"
    env_file: .env

  # elasticsearch:
  #   container_name: es_server
  #   build: ./compose/elasticsearch
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   env_file: .env
    
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: ./compose/django/development/Dockerfile
    command: /start.sh
    depends_on:
      # - elasticsearch
      - postgres
    env_file: .env
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres

volumes:
  # esdata:
  #   driver: local
  postgres_data_dev:
    driver: local
  postgres_backup_dev:
    driver: local
